model_params:
  model: SimpleNet

args:
  expdir: "mnist_simple"
  logdir: "./logs/mnist_simple"

stages:

  data_params:
    batch_size: 64
    num_workers: 0

  state_params:
    main_metric: &reduce_metric precision01
    minimize_metric: False

  criterion_params:
      criterion: CrossEntropyLoss

  optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [1]
    gamma: 0.3

  stage1:
    state_params:
      num_epochs: &num_epochs 3

    callbacks_params:
      loss:
        callback: LossCallback
      optimizer:
        callback: OptimizerCallback
      precision:
        callback: PrecisionCallback
        precision_args: [1, 3, 5]
#      scheduler:
#        callback: OneCycleLR
#        cycle_len: *num_epochs
#        div_factor: 3
#        increase_fraction: 0.25
#        momentum_range: [0.95, 0.85]
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
